### ISSUE TITLE
Index out of range error when pop the priority queue.

### ISSUE THREAD

**Issue by chromato99** [chromato99/WiFi_Positioning_Server_go#1]
```
panic: runtime error: index out of range [-1]

goroutine 41 [running]:
github.com/chromato99/WiFi_Positioning_Server_go/result.(*ResultList).Pop(...)
        /home/admin/go/src/WiFi_Positioning_Server_go/result/result.go:40
github.com/chromato99/WiFi_Positioning_Server_go/core.CalcPos({0x40004d00c0?, 0x4?, 0x0?}, {{0x0, 0x0}, {0x0, 0x0}, {0x400044a840, 0x17, 0x1c}}, ...)
        /home/admin/go/src/WiFi_Positioning_Server_go/core/core.go:281 +0x3f4
created by github.com/chromato99/WiFi_Positioning_Server_go/core.FindPosition
        /home/admin/go/src/WiFi_Positioning_Server_go/core/core.go:236 +0x574
exit status 2
```

The size of the priority queue is 0, but the pop function is sometimes called. Therefore, the out of range runtime error is occurred.

I suspect there is a problem on line 279.

**Comment by chromato99** [comment]
In the for init statement on core.go line 279, result_list was popped once, but it was a problem caused by popping again without checking the range.
